export default {
    LOAD_STATUS_PRODUCTS: "LOAD_STATUS_PRODUCTS",
    SET_PRODUCT: "SET_PRODUCT",
    ADDED_PRODUCT: "ADDED_PRODUCT",
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCT: "GET_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    DELETED_PRODUCT: "DELETED_PRODUCT",
};
