export default {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    FETCH_PRODUCT: "FETCH_PRODUCT",
    LOAD_STATUS_PRODUCTS: "LOAD_STATUS_PRODUCTS",
    SET_PRODUCT: "SET_PRODUCT",
    GET_PRODUCT: "GET_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
};
